import {
  analysisSystemPrompt,
  type MeetingAnalysis
} from "@/mcp-server/src/llm/schemas";
import { normalizeMeetingAnalysis } from "@/mcp-server/src/llm/ollama";

type GroqChatResponse = {
  choices?: Array<{
    message?: {
      content?: string;
    };
  }>;
};

type GroqTranscriptionResponse = {
  text?: string;
};

const GROQ_API_BASE_URL = "https://api.groq.com/openai/v1";
const DEFAULT_GROQ_MODEL = "llama-3.1-8b-instant";
const DEFAULT_GROQ_TRANSCRIPTION_MODEL = "whisper-large-v3-turbo";

function getGroqApiKey() {
  const apiKey = process.env.GROQ_API_KEY;

  if (!apiKey) {
    throw new Error("GROQ_API_KEY is required when using Groq.");
  }

  return apiKey;
}

function parseJsonContent(content: string) {
  const trimmed = content.trim();
  const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);

  return JSON.parse(fenced?.[1] ?? trimmed);
}

export async function analyzeTranscriptWithGroq(
  transcript: string
): Promise<MeetingAnalysis> {
  const response = await fetch(`${GROQ_API_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${getGroqApiKey()}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: process.env.GROQ_MODEL ?? DEFAULT_GROQ_MODEL,
      temperature: 0.1,
      response_format: { type: "json_object" },
      messages: [
        {
          role: "system",
          content: [
            analysisSystemPrompt,
            "The transcript may be generated by speech-to-text and may have weak punctuation, no speaker labels, repeated words, or imperfect sentence boundaries.",
            "Infer structure from conversational intent, but do not invent facts.",
            "Always identify 1-5 topics when the transcript has meaningful content.",
            "For decisions, include firm commitments, agreements, approvals, launch dates, selected plans, and settled next steps, even when the word decided is not used.",
            "For actionItems, include tasks expressed with will, need to, please, can you, I will, or we should.",
            "Return only valid JSON with title, summary, actionItems, decisions, topics, and followUpQuestions."
          ].join(" ")
        },
        { role: "user", content: transcript }
      ]
    })
  });

  if (!response.ok) {
    throw new Error(`Groq analysis failed with status ${response.status}.`);
  }

  const payload = (await response.json()) as GroqChatResponse;
  const content = payload.choices?.[0]?.message?.content;

  if (!content) {
    throw new Error("Groq returned an empty analysis response.");
  }

  return normalizeMeetingAnalysis(parseJsonContent(content), transcript);
}

export async function answerWithGroq(query: string, context: string) {
  const response = await fetch(`${GROQ_API_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${getGroqApiKey()}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: process.env.GROQ_MODEL ?? DEFAULT_GROQ_MODEL,
      temperature: 0.2,
      messages: [
        {
          role: "system",
          content: [
            "You answer questions about meeting history using only the provided source notes.",
            "Do not invent facts. If the sources are not enough, say what is missing.",
            "Write a concise executive answer in plain text.",
            "Mention source numbers like [1] or [2] where useful."
          ].join(" ")
        },
        {
          role: "user",
          content: [
            `Question: ${query}`,
            "",
            "Source notes:",
            context
          ].join("\n")
        }
      ]
    })
  });

  if (!response.ok) {
    throw new Error(`Groq answer model failed with status ${response.status}.`);
  }

  const payload = (await response.json()) as GroqChatResponse;
  const answer = payload.choices?.[0]?.message?.content?.trim();

  if (!answer) {
    throw new Error("Groq returned an empty answer response.");
  }

  return answer;
}

export async function transcribeAudioWithGroq(input: {
  audioBase64: string;
  fileName: string;
  mimeType: string;
}) {
  const audioBytes = Buffer.from(input.audioBase64, "base64");
  const formData = new FormData();

  formData.append(
    "file",
    new Blob([audioBytes], { type: input.mimeType }),
    input.fileName
  );
  formData.append(
    "model",
    process.env.GROQ_TRANSCRIPTION_MODEL ?? DEFAULT_GROQ_TRANSCRIPTION_MODEL
  );
  formData.append("response_format", "json");
  formData.append("temperature", "0");

  const response = await fetch(`${GROQ_API_BASE_URL}/audio/transcriptions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${getGroqApiKey()}`
    },
    body: formData
  });

  if (!response.ok) {
    throw new Error(`Groq transcription failed with status ${response.status}.`);
  }

  const payload = (await response.json()) as GroqTranscriptionResponse;
  const transcript = payload.text?.trim();

  if (!transcript) {
    throw new Error("Groq returned an empty transcription response.");
  }

  return { transcript };
}
